const STATUSES = [
  "Ready to Deploy",
  "Idle",
  "In Use",
  "Broken",
  "EOL",
  "E-waste Pending",
  "E-Wasted",
  "Archived",
  "Borrowed",
  "Lent",
];

const ACTIVE_STATUSES = new Set(["Ready to Deploy", "Idle", "In Use", "Broken", "EOL", "E-waste Pending", "Borrowed", "Lent"]);
const AVAILABLE_STATUSES = new Set(["Ready to Deploy", "Idle", "Borrowed"]);
const EXCEPTION_STATUSES = new Set(["Broken", "EOL", "E-waste Pending"]);

const TEAM_MEMBERS = [
  ["Armin Khosravi", "armin.khosravi@nvidia.com", "akhosravi"],
  ["Ben Siemens", "ben.siemens@nvidia.com", "bsiemens"],
  ["Chris David", "chris.david@nvidia.com", "cdavid"],
  ["Denny Srun", "denny.srun@nvidia.com", "dsrun"],
  ["Gaurav Mehta", "gamehta@nvidia.com", "gamehta"],
  ["Gladson Barbosa", "gladson.barbosa@nvidia.com", "gbarbosa"],
  ["Ilia Makeev", "ilia.makeev@nvidia.com", "imakeev"],
  ["James Taylor", "james.taylor@nvidia.com", "jtaylor"],
  ["Javier Marquez", "javier.marquez@nvidia.com", "jmarquez"],
  ["Jiqing Wang", "jiqing.wang@nvidia.com", "jwang"],
  ["Karthikeyan Somasundaram", "karthikeyan.somasundaram@nvidia.com", "ksomasundaram"],
  ["Kevin Okubo", "kevin.okubo@nvidia.com", "kokubo"],
  ["Leland Gee", "leland.gee@nvidia.com", "lgee"],
  ["Linh Morales", "linh.morales@nvidia.com", "lmorales"],
  ["Monica Martin", "monica.martin@nvidia.com", "mmartin"],
  ["Vince DeMaso", "vince.demaso@nvidia.com", "vdemaso"],
  ["Zachariah Zachariah", "zachariah.zachariah@nvidia.com", "zzachariah"],
  ["Igor Margulis", "igor.margulis@nvidia.com", "imargulis"],
];

const COMMON_FIELDS = [
  ["category", "Category", "select", 1],
  ["model", "Model", "text", 1],
  ["serial", "Serial No.", "text", 0],
  ["assetTag", "Asset Tag", "text", 0],
  ["status", "Status", "select", 1],
  ["owner", "Owner / Assignee", "select", 0],
  ["nvbug", "NVBug #", "text", 0],
  ["stamp", "Stamp", "date", 0],
  ["location", "Location", "select", 1],
  ["usage", "Usage", "text", 0],
  ["borrowedLent", "Borrowed/Lent", "select", 0],
  ["notes", "Notes", "textarea", 0],
];

const CATEGORY_PROFILES = [
  {
    slug: "gpu",
    name: "GPU",
    prefix: "GPU",
    description: "Graphics cards and accelerator inventory.",
    fields: [
      ["arriveDate", "Arrive Date", "date", 0],
      ["chip", "Chip", "text", 0],
      ["sku", "SKU", "text", 0],
      ["gpuClass", "GPU Class", "select", 0, ["GeForce", "RTX", "Data Center", "Professional"]],
      ["edition", "Edition", "text", 0],
      ["maker", "Maker", "text", 0],
    ],
    models: ["RTX Pro 6000", "H100 SXM", "L40S Ada", "RTX 5090 Lab"],
  },
  {
    slug: "dpu",
    name: "DPU",
    prefix: "DPU",
    description: "DPU and NIC-style networking devices.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["openPartNo", "Open Part No.", "text", 1],
      ["psid", "PSID", "text", 0],
      ["opnFamily", "OPN Family", "text", 0],
      ["edition", "Edition", "text", 0],
    ],
    models: ["BF2 DPU", "BF3 DPU", "ConnectX-6", "ConnectX-7"],
  },
  {
    slug: "converged-gpu-dpu",
    name: "Converged GPU+DPU",
    prefix: "CGD",
    description: "Combined accelerator and DPU assets.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["sku", "SKU", "text", 0],
      ["edition", "Edition", "text", 0],
    ],
    models: ["A100+BF2 Pilot", "A30+BF2 Pilot", "H100+BF3 Pilot"],
  },
  {
    slug: "server",
    name: "Server",
    prefix: "SRV",
    description: "Lab servers and shared compute systems.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["ip", "IP", "text", 0],
      ["cpu", "CPU", "text", 0],
      ["motherBoard", "Mother Board", "text", 0],
      ["memory", "Memory", "text", 0],
      ["disk", "Disk", "text", 0],
      ["nvAssetNumber", "NV Asset Number", "text", 0],
    ],
    models: ["HGX Lab Server", "DGX Test Node", "PowerEdge R760", "Supermicro SYS-420"],
  },
  {
    slug: "workstation",
    name: "Workstation",
    prefix: "WKS",
    description: "Personal and shared lab workstations.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["ip", "IP", "text", 0],
      ["cpu", "CPU", "text", 0],
      ["motherBoard", "Mother Board", "text", 0],
      ["memory", "Memory", "text", 0],
      ["disk", "Disk", "text", 0],
    ],
    models: ["Precision 7960 Tower", "ThinkStation P7", "Z8 G5 Workstation", "Precision 5670 Tower"],
  },
  {
    slug: "pc",
    name: "PC",
    prefix: "PC",
    description: "Testing PCs and bench systems.",
    fields: [
      ["arriveDate", "Arrive Date", "date", 0],
      ["cpu", "CPU", "text", 1],
      ["motherBoard", "Mother Board", "text", 0],
      ["gpu", "GPU", "text", 0],
      ["memory", "Memory", "text", 0],
      ["disk", "Disk", "text", 0],
      ["psu", "PSU", "text", 0],
    ],
    models: ["ROG Lab PC", "Aorus Bench PC", "OptiPlex Test PC"],
  },
  {
    slug: "switch",
    name: "Switch",
    prefix: "SWT",
    description: "Network switches and fabric devices.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["ip", "IP", "text", 0],
      ["type", "Type", "select", 0, ["ETH", "IB", "RJ45"]],
    ],
    models: ["Spectrum SN3700", "Quantum QM8700", "SN2100 Rack Switch"],
  },
  {
    slug: "mobile",
    name: "Mobile",
    prefix: "MOB",
    description: "Phones, tablets, notebooks, and mobile lab devices.",
    fields: [
      ["setupDate", "Setup Date", "date", 0],
      ["maker", "Maker", "text", 0],
      ["cpu", "CPU", "text", 0],
      ["memory", "Memory", "text", 0],
      ["gpu", "GPU", "text", 0],
      ["disk", "Disk", "text", 0],
      ["resolution", "Resolution", "text", 0],
    ],
    models: ["Notebook Lab Kit", "Tablet Validation Kit", "Mobile Test Phone"],
  },
  {
    slug: "monitor",
    name: "Monitor",
    prefix: "MON",
    description: "Displays and visual test equipment.",
    fields: [
      ["arriveDate", "Arrive Date", "date", 0],
      ["maker", "Maker", "text", 0],
      ["nativeResolution", "Native Resolution", "text", 1],
      ["refreshRate", "Refresh Rate", "text", 0],
      ["connector", "Connector", "text", 0],
      ["features", "Features", "text", 0],
    ],
    models: ["ProArt 32 Display", "Odyssey Validation Display", "UltraSharp Lab Monitor"],
  },
  {
    slug: "cable",
    name: "Cable",
    prefix: "CBL",
    description: "Tracked lab cables and interconnects.",
    fields: [
      ["arriveDate", "Arrive Date", "date", 0],
      ["oldLocation", "Old Location", "text", 0],
    ],
    models: ["QSFP Cable 2m", "SFP28 Cable 3m", "C13-C14 Power Cable"],
  },
  {
    slug: "misc",
    name: "MISC",
    prefix: "MSC",
    description: "Other tracked hardware and lab parts.",
    fields: [["arriveDate", "Arrive Date", "date", 0]],
    models: ["NVLink Bridge Kit", "Breakout Box", "Storage Adapter"],
  },
  {
    slug: "low-price-consumables",
    name: "Low-price Consumables",
    prefix: "LPC",
    description: "Quantity-based consumables and low-cost items.",
    fields: [
      ["quantity", "Quantity", "number", 1],
      ["requester", "Requester", "select", 0],
      ["arriveDate", "Arrive Date", "date", 0],
    ],
    models: ["USB-C Adapter Pack", "Network Cable Bundle", "Lab Label Roll"],
  },
  {
    slug: "e-waste",
    name: "E-Waste",
    prefix: "EWS",
    description: "Retired and disposal-tracked devices.",
    fields: [["arriveDate", "Arrive Date", "date", 0]],
    models: ["Retired GPU Board", "Retired Server Node", "Retired Monitor"],
  },
  {
    slug: "broken-devices",
    name: "Broken Devices",
    prefix: "BRK",
    description: "Repair and disposition exception queue.",
    fields: [
      ["problem", "Problem", "textarea", 1],
      ["eWastePending", "E-Waste-Pending", "select", 0, ["Yes", "No"]],
    ],
    models: ["Broken GPU Board", "Broken Lab Server", "Broken Cable Assembly"],
  },
];

const IMPORT_PROFILES = [
  { id: "assets-gpu", label: "Assets - GPU", categorySlug: "gpu", required: ["model", "serial", "assetTag", "status", "location"] },
  { id: "assets-dpu", label: "Assets - DPU", categorySlug: "dpu", required: ["model", "serial", "assetTag", "status", "location", "openPartNo"] },
  { id: "assets-converged", label: "Assets - Converged GPU+DPU", categorySlug: "converged-gpu-dpu", required: ["model", "serial", "assetTag", "status", "location"] },
  { id: "assets-systems", label: "Assets - Server/Workstation/PC", categorySlug: "", required: ["category", "model", "serial", "assetTag", "status", "location"] },
  { id: "assets-switch", label: "Assets - Switch", categorySlug: "switch", required: ["model", "serial", "assetTag", "status", "location"] },
  { id: "assets-mobile-monitor-cable-misc", label: "Assets - Mobile/Monitor/Cable/MISC", categorySlug: "", required: ["category", "model", "assetTag", "status", "location"] },
  { id: "low-price-consumables", label: "Low-price Consumables", categorySlug: "low-price-consumables", required: ["model", "assetTag", "status", "location", "quantity"] },
  { id: "e-waste-broken", label: "E-Waste/Broken Devices", categorySlug: "", required: ["category", "model", "assetTag", "status", "location"] },
  { id: "locations", label: "Locations", referenceType: "locations", required: ["location"] },
  { id: "users-owners", label: "Users/Owners", referenceType: "owners", required: ["name", "email"] },
  { id: "manufacturers-suppliers", label: "Manufacturers/Suppliers", referenceType: "suppliers", required: ["name"] },
];

const ALIASES = new Map(Object.entries({
  "full name": "name",
  "name": "name",
  "email": "email",
  "username": "username",
  "item name": "model",
  "part name": "model",
  "model": "model",
  "model name": "model",
  "category": "category",
  "manufacturer": "manufacturer",
  "maker": "manufacturer",
  "model number": "modelNumber",
  "serial": "serial",
  "serial no.": "serial",
  "serial no": "serial",
  "serial number": "serial",
  "asset tag": "assetTag",
  "location": "location",
  "notes": "notes",
  "purchase date": "purchaseDate",
  "purchase cost": "purchaseCost",
  "company": "company",
  "status": "status",
  "warranty": "warranty",
  "supplier": "supplier",
  "nvbug": "nvbug",
  "nvbug #": "nvbug",
  "jira ticket": "nvbug",
  "jira link": "nvbug",
  "open part no.": "openPartNo",
  "open part no": "openPartNo",
  "psid": "psid",
  "opn family": "opnFamily",
  "quantity": "quantity",
  "requester": "requester",
  "chip": "chip",
  "sku": "sku",
  "gpu class": "gpuClass",
  "edition": "edition",
  "ip": "ip",
  "cpu": "cpu",
  "mother board": "motherBoard",
  "memory": "memory",
  "disk": "disk",
  "psu": "psu",
  "problem": "problem",
  "e-waste-pending": "eWastePending",
}));

module.exports = {
  STATUSES,
  ACTIVE_STATUSES,
  AVAILABLE_STATUSES,
  EXCEPTION_STATUSES,
  TEAM_MEMBERS,
  COMMON_FIELDS,
  CATEGORY_PROFILES,
  IMPORT_PROFILES,
  ALIASES,
};
